[mypy]
python_version = 3.11
ignore_missing_imports = True
warn_return_any = False
disallow_untyped_defs = False

# Игнорируем ошибки типов для конкретных модулей
[mypy-tp_server.app.logging_config]
ignore_errors = True

[mypy-tp_server.app.config]
ignore_errors = True

[mypy-tp_server.app.forecast]
ignore_errors = True

[mypy-tp_server.app.news]
ignore_errors = True